iio-buffer-utils: Add unused result check
With

       CPPFLAGS='-D_FORTIFY_SOURCE=2'   ./configure

we otherwise fail like

iio-buffer-utils.c: In function ‘_write_sysfs_int’:
iio-buffer-utils.c:386:3: error: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Werror=unused-result]
  386 |   fscanf(sysfsfp, "%d", &test);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
iio-buffer-utils.c: In function ‘_write_sysfs_string’:
iio-buffer-utils.c:434:2: error: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Werror=unused-result]
  434 |  fscanf(sysfsfp, "%s", temp);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
iio-buffer-utils.c: In function ‘build_channel_array’:
iio-buffer-utils.c:263:4: error: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Werror=unused-result]
  263 |    fscanf (sysfsfp, "%d", &ret);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
iio-buffer-utils.c:291:4: error: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Werror=unused-result]
  291 |    fscanf (sysfsfp, "%u", &current->index);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
iio-buffer-utils.c: In function ‘iioutils_get_param_float’:
iio-buffer-utils.c:171:3: error: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Werror=unused-result]
  171 |   fscanf (sysfsfp, "%f", output);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors